[package]
name = "tftp"
version = "0.2.0"
authors = ["9506hqwy"]
edition = "2021"
rust-version = "1.60"
repository = "https://github.com/9506hqwy/tftp-rs"
license = "MIT OR Apache-2.0"
keywords = ["rfc1350", "rfc2347", "rfc2348", "rfc2349", "rfc7440"]
categories = ["network-programming"]

[dependencies]
bytes = "1.4.0"
log = "0.4.19"

[dependencies.tokio]
version = "1.32.0"
features = ["fs", "io-util", "macros", "net", "rt-multi-thread", "sync", "time"]

[dev-dependencies]
clap = "4.3.21"
env_logger = "0.10.0"

[[example]]
name = "tftp"

[[example]]
name = "tftpd"

[profile.release]
strip = "symbols"
lto = true
